config/routes.rb
Rails.application.routes.draw do

  get '/ventas/:id/cambiar' => 'venta#cambiar'
  get 'atencions/:id/asignar_mascota'=>'atencions#asignar_mascota'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  
  get '/mascota/:id/atenciones' => 'mascota#atenciones'

  get '/clientes/buscar' => 'clientes#buscar'
  get '/mascota/buscar' => 'mascota#buscar'
  get '/veterinarios/buscar' => 'veterinarios#buscar'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  get '/prodcutos/:id/modificar' => 'prodcutos#modificar'
  get '/prodcutos/:id/reabastecer' => 'prodcutos#reabastecer'
  get '/turnos/:id/atendiendo' => 'turnos#atendiendo'
  get '/turnos/:id/atendido' => 'turnos#atendido'

  get 'welcome/index'
  get 'veterinaria'=> 'welcome#index'
  get 'About'=> 'welcome#about'
  get 'Contact'=> 'welcome#contact'
  get 'contact/index'
  get 'about/index'
  resources :atencions
  resources :turnos
  resources :lists
  resources :venta
  resources :clientes
  resources :veterinarios
  resources :mascota
  resources :prodcutos
  resources :clientes

   root 'welcome#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	EMAIL_REGEX = /\A([a-z0-9][\._\-]?)+@(\w)+(\.([a-z])+)+\z/i
	validates :ci, :uniqueness=>{message:"Ya esta registrado"}
	validates :ci,:presence=>{message: "No puede estar vacio"}
	validates :nombre,:presence=>{message: "No puede estar vacio"}
	validates :apellido,:presence=>{message: "No puede estar vacio"}
	validates :telefono,:presence=>{message: "No puede estar vacio"}
	validates :correo,:presence=>{message: "No puede estar vacio"}
	validates :correo, uniqueness: true,format: {with:  EMAIL_REGEX,message:"Formato invalido	"}
	has_many :mascotums
	has_many :atencions
	has_many :ventums
	before_create :correo?

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show

  end
  def ventas
    @cliente = Cliente.find(params[:id])
  end
  def buscar
    @clientes =  Cliente.where("nombre like :name1 or apellido like :name1 or ci like :name1", {:name1 => "%#{params[:searchbox]}%"})
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente fue modificado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:ci, :nombre, :apellido, :telefono, :correo)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<style type="text/css">
   label{
    color:white;
   }
</style>
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div class="container">
    <div class="alert alert-danger" role="alert">
      <font color="black"><h2><%= pluralize(@cliente.errors.count, "Error(s)") %> <br>No se guardara este Cliente:</h2></font>
      <% @cliente.errors.full_messages.each do |message| %>
        <font color="black"><li><%= message %></li></font>
      <% end %>
    </div>
  </div>
  <% end %>
  <div class="field, container">
    <table class="table">
      <tr>
        <td><%= f.label :ci %></td>
        <td><%= f.number_field :ci %></td>
      </tr>
      <tr>
        <td><%= f.label :nombre %></td>
        <td><%= f.text_field :nombre %></td>
      </tr>
      <tr>
        <td><%= f.label :apellido %></td>
        <td><%= f.text_field :apellido %></td>
      </tr>
      <tr>
        <td><%= f.label :telefono %></td>
        <td><%= f.number_field :telefono %></td>
      </tr>
      <tr>
        <td><%= f.label :correo %></td>
        <td><%= f.text_field :correo %></td>
      </tr>
    </table>
  </div>
</br>
  <div class="actions">
    <%= f.submit 'Guardar',class:"big ui button, ui inverted olive button"%>
  </div>
</br>

<% end %>

app/views/clientes/buscar.html.erb
<style type="text/css">
  thead{
    color:white;
  }
   td{
    background-color: white;
   }

  h1{
    color:white;
  }
</style>

<p id="notice"><%= notice %></p>

<h1>Lista de Clientes</h1>

<div class="row">

 <div class="col-md-6 col-md-offset-3">
  <%= form_tag({:controller => "clientes", :action => "buscar"}, :method => :get) do %>

    <%= label_tag("") %>

  <%= text_field_tag(:searchbox) %>

<%= submit_tag "Buscar" , class: "btn btn-info" %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Ci</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.ci %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.correo %></td>
        <td><%= link_to 'Ver', cliente, class: "btn btn-info"%></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) ,class: "btn btn-warning"%></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

</div>

<br>

<%= link_to 'Registrar Cliente', new_cliente_path, class: "btn btn-success" %>
<a class="btn btn-primary" href="/veterinaria">Home</a>

app/views/clientes/edit.html.erb
<style type="text/css">
  h1{
    color:white;
   }

  
</style>
<h1>Editar Cliente</h1>

<%= render 'form' %>

<%= link_to 'Ver', @cliente, class:"btn btn-info"%>
<%= link_to 'Lista de Clientes', clientes_path , class:"btn btn-primary"%>

app/views/clientes/index.html.erb
<style type="text/css">
  thead{
    color:white;
  }
   td{
    background-color: white;
   }

  h1{
    color:white;
  }
</style>

<p id="notice"><%= notice %></p>

<h1>Lista de Clientes</h1>

<div class="row">

 <div class="col-md-6 col-md-offset-3">
  <%= form_tag({:controller => "clientes", :action => "buscar"}, :method => :get) do %>

    <%= label_tag("") %>

  <%= text_field_tag(:searchbox) %>

<%= submit_tag "Buscar" , class: "btn btn-info" %>
<% end %>
<div id="muestra">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Ci</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.ci %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.correo %></td>
        <td><%= link_to 'Ver', cliente, class: "btn btn-info"%></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) ,class: "btn btn-warning"%></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Esta seguro?' } , class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

<br>

<%= link_to 'Registrar Cliente', new_cliente_path, class: "btn btn-success" %>
<a class="btn btn-primary" href="veterinaria">Home</a>

app/views/clientes/new.html.erb
<style type="text/css">
   h1{
    color:white;
   }
</style>
<h1>Nuevo Cliente</h1>

<%= render 'form'%>

<%= link_to 'Lista de Clientes', clientes_path , class:"big ui button, ui inverted blue button"%>

app/views/clientes/show.html.erb
<style type="text/css">
  p{
    color:white;
   }
   td{
    background-color: white;
   }
   thead{
    color:white;
   }
   strong{
    color:white;
   }
   #botones{
     font:black;
   }

</style>
<div id="muestra">
<h1><strong>Datos del Cliente </strong></h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Ci:</strong>
  <%= @cliente.ci %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @cliente.apellido %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @cliente.correo %>
</p>

<p><strong>Mascotas del Dueño:</strong><p>
<br>
<br>
<div class="row">
<div class="col-md-4 col-md-offset-4">
<%if@cliente.mascotums.count>0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Especie</th>
      <th>Raza</th>
      <th>Fecha nacimiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <% @cliente.mascotums.each do |mascotum| %>
        <tr>
          <td><%= mascotum.nombre %></td>
          <td><%= mascotum.especie %></td>
          <td><%= mascotum.raza %></td>
          <td><%= mascotum.fecha_nacimiento %></td>
          <td><%= link_to 'Ver', mascotum , class: "btn btn-info" %></td>
          <td><%= link_to 'Editar', edit_mascotum_path(mascotum) , class: "btn btn-warning"%></td>
          <td><%= link_to 'Eliminar', mascotum, method: :delete, data: { confirm: 'Esta seguro?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    <%else%>
      <strong>No hay mascotas disponible</strong>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>
<div id="botones">
  <%= link_to 'Historial de compras', '/clientes/'+@cliente.id.to_s+'/ventas' , class: "btn btn-success" %>

<%= link_to 'Registrar Mascota', new_mascotum_path , class: "btn btn-success" %>
<%= link_to 'Editar', edit_cliente_path(@cliente), class: "btn btn-warning" %>
<%= link_to 'Lista de Clientes', clientes_path , class: "btn btn-primary"%>
</div>

app/views/clientes/ventas.html.erb
<style type="text/css">
  p{
    color:white;
   }
   td{
    background-color: white;
   }
   thead{
    color:white;
   }
   strong{
    color:white;
   }

</style>

<h1><strong>Compras del cliente </strong></h1>
<p>Total pagado : <%= @cliente.ventums.sum(:Costo) %></p>
<div class="row">
<div class="col-md-4 col-md-offset-4">
<%if@cliente.ventums.count>0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id venta</th>
      <th>Costo (Bs)</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cliente.ventums.each do |ventum| %>
      <tr>
        <td><%= ventum.id %></td>
        <td><%= ventum.Costo %></td>
        <td><%= link_to 'Mostrar', ventum, class: "btn btn-info" %></td>
        <td><%= link_to 'Eliminar', ventum, method: :delete, data: { confirm: 'Estas seguro?' }, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<%else%>
<p>No hay ventas registradas</p>
<%end%>
<%= link_to 'Atras', '/clientes/'+@cliente.id.to_s+'' , class: "btn btn-success" %>