config/routes.rb
Rails.application.routes.draw do

  get '/ventas/:id/cambiar' => 'venta#cambiar'
  get 'atencions/:id/asignar_mascota'=>'atencions#asignar_mascota'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  
  get '/mascota/:id/atenciones' => 'mascota#atenciones'

  get '/clientes/buscar' => 'clientes#buscar'
  get '/mascota/buscar' => 'mascota#buscar'
  get '/veterinarios/buscar' => 'veterinarios#buscar'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  get '/prodcutos/:id/modificar' => 'prodcutos#modificar'
  get '/prodcutos/:id/reabastecer' => 'prodcutos#reabastecer'
  get '/turnos/:id/atendiendo' => 'turnos#atendiendo'
  get '/turnos/:id/atendido' => 'turnos#atendido'

  get 'welcome/index'
  get 'veterinaria'=> 'welcome#index'
  get 'About'=> 'welcome#about'
  get 'Contact'=> 'welcome#contact'
  get 'contact/index'
  get 'about/index'
  resources :atencions
  resources :turnos
  resources :lists
  resources :venta
  resources :clientes
  resources :veterinarios
  resources :mascota
  resources :prodcutos
  resources :clientes

   root 'welcome#index'

end

app/models/veterinario.rb
class Veterinario < ActiveRecord::Base
  EMAIL_REGEX = /\A([a-z0-9][\._\-]?)+@(\w)+(\.([a-z])+)+\z/i
  has_many :atencions
  validates :ci, :uniqueness=>{message:"Ya esta registrado"}
	validates :ci,:presence=>{message: "No puede estar vacio"}
	validates :nombre,:presence=>{message: "No puede estar vacio"}
	validates :apellido,:presence=>{message: "No puede estar vacio"}
	validates :telefono,:presence=>{message: "No puede estar vacio"}
	validates :correo,:presence=>{message: "No puede estar vacio"}
  validates :especialidad,:presence=>{message: "No puede estar vacio"}

	validates :correo, uniqueness: true,format: {with:  EMAIL_REGEX,message:"Formato invalido	"}

end

app/controllers/veterinarios_controller.rb
class VeterinariosController < ApplicationController
  before_action :set_veterinario, only: [:show, :edit, :update, :destroy]

  # GET /veterinarios
  # GET /veterinarios.json
  def index
    @veterinarios = Veterinario.all
  end

  # GET /veterinarios/1
  # GET /veterinarios/1.json
  def show
  end

  # GET /veterinarios/new
  def new
    @veterinario = Veterinario.new
  end

  # GET /veterinarios/1/edit
  def edit
  end
  def buscar
    @veterinarios =  Veterinario.where("nombre like :name1 or apellido like :name1 or ci like :name1", {:name1 => "%#{params[:searchbox]}%"})
  end
  # POST /veterinarios
  # POST /veterinarios.json
  def create
    @veterinario = Veterinario.new(veterinario_params)

    respond_to do |format|
      if @veterinario.save
        format.html { redirect_to @veterinario, notice: 'Veterinario fue creado satisfactoriamente!' }
        format.json { render :show, status: :created, location: @veterinario }
      else
        format.html { render :new }
        format.json { render json: @veterinario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veterinarios/1
  # PATCH/PUT /veterinarios/1.json
  def update
    respond_to do |format|
      if @veterinario.update(veterinario_params)
        format.html { redirect_to @veterinario, notice: 'Veterinario fue modificado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @veterinario }
      else
        format.html { render :edit }
        format.json { render json: @veterinario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veterinarios/1
  # DELETE /veterinarios/1.json
  def destroy
    @veterinario.destroy
    respond_to do |format|
      format.html { redirect_to veterinarios_url, notice: 'Veterinario fue eliminado satisfactoriamente!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veterinario
      @veterinario = Veterinario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veterinario_params
      params.require(:veterinario).permit(:ci, :nombre, :apellido, :telefono, :correo, :especialidad)
    end
end

app/helpers/veterinarios_helper.rb
module VeterinariosHelper
end

app/views/veterinarios/_form.html.erb
<style type="text/css">
   label{
    color:white;
   }
   h1{
     color: white;
   }
</style>
<%= form_for(@veterinario) do |f| %>
  <% if @veterinario.errors.any? %>
  <div class="container">
    <div class="alert alert-danger" role="alert">
      <font color="black"><h2><%= pluralize(@veterinario.errors.count, "error") %> prohibited this veterinario from being saved:</h2></font>

      <ul>
      <% @veterinario.errors.full_messages.each do |message| %>
        <font color="black"><li><%= message %></li></font>
      <% end %>
      </ul>
    </div>
    </div>

  <% end %>

  <div class="field, container">
    <table class="table">
      <tr>
      <td><%= f.label :ci %></td>
      <td><%= f.number_field :ci %></td>
    </tr>
    <tr>
      <td><%= f.label :nombre %></td>
      <td><%= f.text_field :nombre %></td>
  </tr>
    <tr>
      <td><%= f.label :apellido %></td>
      <td><%= f.text_field :apellido %></td>
  </tr>
    <tr>
      <td><%= f.label :telefono %></td>
      <td><%= f.number_field :telefono %></td>
  </tr>
    <tr>
      <td><%= f.label :correo %></td>
      <td><%= f.text_field :correo %></td>
  </tr>
  <tr>
    <td><%= f.label :especialidad %></td>
    <% especialidades = {'Medico'=> 'Medico','Ayudante'=> 'Ayudante','Estudiante veterinario'=>'EstudianteVeterinario','Tecnico en peluquero'=>'TecnicoPeluquero', 'Peluquero'=>'Peluquero', 'Master especialista en peluqueria y estetica canina'=>'MasterEspecialistaPeluquero'} %>
    <% lista = especialidades.sort %>
    <td><%= f.select :especialidad, lista %></td>
</tr>
</table>
  </div>


  <div class="actions">
    <%= f.submit 'Guardar', class:"big ui button, ui inverted olive button" %>
  </div>
<% end %>

app/views/veterinarios/buscar.html.erb
<style type="text/css">

  h1{
    color:white;
   }

   thead{
    color:white;
   }

    td{
    background-color: white;
   }

</style>
<p id="notice"><%= notice %></p>
<div id="muestra">
<h1><strong>Lista Veterinarios</strong></h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">

  <%= form_tag({:controller => "veterinarios", :action => "buscar"}, :method => :get) do %>

    <%= label_tag("") %>

  <%= text_field_tag(:searchbox) %>

<%= submit_tag "Buscar" , class: "btn btn-info" %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Ci</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th>Especialidad</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veterinarios.each do |veterinario| %>
      <tr>
        <td><%= veterinario.ci %></td>
        <td><%= veterinario.nombre %></td>
        <td><%= veterinario.apellido %></td>
        <td><%= veterinario.telefono %></td>
        <td><%= veterinario.correo %></td>
        <td><%= veterinario.especialidad %></td>

        <td><%= link_to 'Ver', veterinario ,class: "btn btn-info"%></td>
        <td><%= link_to 'Editar', edit_veterinario_path(veterinario),class: "btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', veterinario, method: :delete, data: { confirm: 'Esta seguro?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>
<%= link_to 'Registrar veterinario', new_veterinario_path , class: "btn btn-success" %>

<a  class="btn btn-primary" href="/veterinaria">Home</a>

app/views/veterinarios/edit.html.erb
<h1>Editing Veterinario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @veterinario %> |
<%= link_to 'Atras', veterinarios_path %>

app/views/veterinarios/index.html.erb
<style type="text/css">

  h1{
    color:white;
   }

   thead{
    color:white;
   }

    td{
    background-color: white;
   }

</style>
<p id="notice"><%= notice %></p>
<div id="muestra">
<h1><strong>Lista Veterinarios</strong></h1>
<div class="row">

<div class="col-md-6 col-md-offset-3">

  <%= form_tag({:controller => "veterinarios", :action => "buscar"}, :method => :get) do %>

    <%= label_tag("") %>

  <%= text_field_tag(:searchbox) %>

<%= submit_tag "Buscar" , class: "btn btn-info" %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Ci</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Correo</th>
      <th>Especialidad</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veterinarios.each do |veterinario| %>
      <tr>
        <td><%= veterinario.ci %></td>
        <td><%= veterinario.nombre %></td>
        <td><%= veterinario.apellido %></td>
        <td><%= veterinario.telefono %></td>
        <td><%= veterinario.correo %></td>
        <td><%= veterinario.especialidad %></td>

        <td><%= link_to 'Ver', veterinario ,class: "btn btn-info"%></td>
        <td><%= link_to 'Editar', edit_veterinario_path(veterinario),class: "btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', veterinario, method: :delete, data: { confirm: 'Esta seguro?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>

<%= link_to 'Nuevo Veterinario', new_veterinario_path, class: "btn btn-success" , style:"color:white"%>
<a  class="btn btn-primary" href="/veterinaria">Home</a>

app/views/veterinarios/new.html.erb
<style type="text/css">
   h1{
    color:white;
   }
</style>
<h1>Nuevo Veterinario</h1>

<%= render 'form' %>

<%= link_to 'Lista de veterinarios', veterinarios_path, class:"big ui button, ui inverted blue button" %>

app/views/veterinarios/show.html.erb
<style type="text/css">

  p{
    color:white;
   }
   td{
    background-color: white;
   }
   thead{
    color:white;
   }
   strong{
    color:white;
   }

</style>
<p id="notice"><%= notice %></p>
<div id="muestra">

<h1><strong>Datos del veterinario</strong></h1>
<p>
  <strong>Ci:</strong>
  <%= @veterinario.ci %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @veterinario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @veterinario.apellido %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @veterinario.telefono %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @veterinario.correo %>
</p>
<p>
  <strong>Especialidad:</strong>
  <%= @veterinario.especialidad %>
</p>
</div>
<%= link_to 'Editar', edit_veterinario_path(@veterinario) , class: "btn btn-warning"%>
<%= link_to 'Atras', veterinarios_path, class: "btn btn-primary" %>