config/routes.rb
Rails.application.routes.draw do

  get '/ventas/:id/cambiar' => 'venta#cambiar'
  get 'atencions/:id/asignar_mascota'=>'atencions#asignar_mascota'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  
  get '/mascota/:id/atenciones' => 'mascota#atenciones'

  get '/clientes/buscar' => 'clientes#buscar'
  get '/mascota/buscar' => 'mascota#buscar'
  get '/veterinarios/buscar' => 'veterinarios#buscar'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  get '/prodcutos/:id/modificar' => 'prodcutos#modificar'
  get '/prodcutos/:id/reabastecer' => 'prodcutos#reabastecer'
  get '/turnos/:id/atendiendo' => 'turnos#atendiendo'
  get '/turnos/:id/atendido' => 'turnos#atendido'

  get 'welcome/index'
  get 'veterinaria'=> 'welcome#index'
  get 'About'=> 'welcome#about'
  get 'Contact'=> 'welcome#contact'
  get 'contact/index'
  get 'about/index'
  resources :atencions
  resources :turnos
  resources :lists
  resources :venta
  resources :clientes
  resources :veterinarios
  resources :mascota
  resources :prodcutos
  resources :clientes

   root 'welcome#index'

end

app/models/atencion.rb
class Atencion < ActiveRecord::Base

	belongs_to :cliente
	belongs_to :mascotum
	belongs_to :veterinario
	validates :anamnesis,:presence=>{message: "No puede estar vacio"}
	validates :temperatura,:presence=>{message: "No puede estar vacio"}
	validates :mucosas,:presence=>{message: "No puede estar vacio"}
	validates :palpacion,:presence=>{message: "No puede estar vacio"}
	validates :diagnostico,:presence=>{message: "No puede estar vacio"}
	validates :tratamiento,:presence=>{message: "No puede estar vacio"}

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	EMAIL_REGEX = /\A([a-z0-9][\._\-]?)+@(\w)+(\.([a-z])+)+\z/i
	validates :ci, :uniqueness=>{message:"Ya esta registrado"}
	validates :ci,:presence=>{message: "No puede estar vacio"}
	validates :nombre,:presence=>{message: "No puede estar vacio"}
	validates :apellido,:presence=>{message: "No puede estar vacio"}
	validates :telefono,:presence=>{message: "No puede estar vacio"}
	validates :correo,:presence=>{message: "No puede estar vacio"}
	validates :correo, uniqueness: true,format: {with:  EMAIL_REGEX,message:"Formato invalido	"}
	has_many :mascotums
	has_many :atencions
	has_many :ventums
	before_create :correo?

end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :ventum
	before_create :add_costo 
	after_create :modificar 
	validate :cantidad?, :cant?,:verdad
	before_destroy :retornar
	def verdad
		if(cantidad==nil )
			errors.add(:cantidad, " no puede ser 0")
		end
	end
	def cant?
		if(cantidad!=nil)
			if (self.cantidad <= 0 ) 
				errors.add(:cantidad, " no puede ser 0")
			end
		end
	end

	def add_costo
		if(cantidad!=nil)
			a=Prodcuto.where(nombre:self.producto).take.Precio
			self.costo =a*self.cantidad
		end
	end

	def modificar
		if(cantidad!=nil)
			a=Prodcuto.where(nombre:self.producto).take
			a.cantidad=a.cantidad-self.cantidad
			a.save
		end
	end

	def retornar
		if(cantidad!=nil)
			a=Prodcuto.where(nombre:self.producto).take
			a.cantidad=a.cantidad+self.cantidad
			a.save
		end
	end

	def cantidad?
		if(cantidad!=nil)
			unless self.cantidad <= Prodcuto.where(nombre:self.producto).take.cantidad
				errors.add(:cantidad, "rebasa en el stock")
			end
		end
	end
end

app/models/mascotum.rb
class Mascotum < ActiveRecord::Base
	belongs_to :cliente
	has_many :atencions
	validates :nombre,:presence=>{message: "No puede estar en blanco"}
	validates :especie,:presence=>{message: "No puede estar en blanco"}
	validates :raza,:presence=>{message: "No puede estar en blanco"}
	validates :fecha_nacimiento,:presence=>{message: "No puede estar en blanco"}
	validates :cliente_id,:presence=>{message: "No puede estar en blanco"}

	before_create :fecha_nac_verdad?
	def fecha_nac_verdad?
		if( fecha_nacimiento < Date.today)
			return true
		else
			errors.add(:fecha_nacimiento, "Debe ser menor a la fecha actual")
			return false
		end
	end
end

app/models/prodcuto.rb
class Prodcuto < ActiveRecord::Base
	validates :codigo, :uniqueness=>{message:"Codigo ya se encuentra registrado"}
	validates :codigo,:presence=>{message: "No puede estar en blanco"}
	validates :nombre,:presence=>{message: "No puede estar en blanco"}
	validates :fecha_vencimiento,:presence=>{message: "No puede estar en blanco"}
	validates :cantidad,:presence=>{message: "No puede estar en blanco"}
	validates :Precio,:presence=>{message: "No puede estar en blanco"}

	before_create :fecha_verdad?, :cantidad_verdad?, :precio_verdad?
	def fecha_verdad?
		if( self.fecha_vencimiento > Date.today)
			return true
		else
			errors.add(:fecha_vencimiento, "Debe ser mayor a la fecha actual")
			return false
		end
	end
	def cantidad_verdad?
		if (self.cantidad < 0)
			errors.add(:cantidad, "No puede ser menor a 0")
			return false
		end
	end
	def precio_verdad?
		if (self.Precio < 0)
			errors.add(:Precio, "No puede ser menor a 0")
			return false
		end
	end
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	before_create :fecha, :estado_espera

	def fecha
		self.actual=Date.today
	end
	def estado_espera
		self.estado="Espera"
	end
end

app/models/ventum.rb
class Ventum < ActiveRecord::Base
	belongs_to :cliente
	has_many :lists
	before_create :set_costo

	before_destroy :retornar
	def set_costo
		self.Costo=0
	end
	def retornar
		List.where(ventum_id:self.id).destroy_all
	end
	def estados
		self.estado = false
	end
end

app/models/veterinario.rb
class Veterinario < ActiveRecord::Base
  EMAIL_REGEX = /\A([a-z0-9][\._\-]?)+@(\w)+(\.([a-z])+)+\z/i
  has_many :atencions
  validates :ci, :uniqueness=>{message:"Ya esta registrado"}
	validates :ci,:presence=>{message: "No puede estar vacio"}
	validates :nombre,:presence=>{message: "No puede estar vacio"}
	validates :apellido,:presence=>{message: "No puede estar vacio"}
	validates :telefono,:presence=>{message: "No puede estar vacio"}
	validates :correo,:presence=>{message: "No puede estar vacio"}
  validates :especialidad,:presence=>{message: "No puede estar vacio"}

	validates :correo, uniqueness: true,format: {with:  EMAIL_REGEX,message:"Formato invalido	"}

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list.ventum, notice: 'Venta exitosa.' }
        format.json { render :show, status: :created, location: @list.ventum }
      else
        format.html { redirect_to @list.ventum, notice: 'Venta no exitosa, insucifiencte stock o cantidad inaceptable.' }
        format.json { render json: @list.ventum.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'Lista cargada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to @list.ventum, notice: 'Lista eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:producto, :costo, :cantidad, :ventum_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atencions_helper.rb
module AtencionsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/mascota_helper.rb
module MascotaHelper
end

app/helpers/prodcutos_helper.rb
module ProdcutosHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/helpers/veterinarios_helper.rb
module VeterinariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<style type="text/css">
	body{
		background-color: #043D2C;
		text-align: center;
		color:white;
	}
</style>
<div id ="muestra">
		<h1><strong> Acerca de la veterinaria:</strong> </h1>
		<%= image_tag "secundarioA.jpg", :alt => "Twitter", :title => "logoVeterinaria",width:"880px",height:"440px"%>
		<h4>Nuestra misión es ofrecer un servicio dedicado y de buen trato,<br> tanto al cliente como a su mascota, esforzándonos en atender las necesidades específicas de cada una de ellas.<br>
Ponemos nuestro mayor empeño en el diagnóstico preciso de las patologías que aquejan a nuestros pacientes,<br> actualizándonos a diario en la clínica de animales de compañía.</h4>
	</div>

app/views/welcome/contact.html.erb
<style type="text/css">
	body{
		background-color: #043D2C;
		text-align: center;
		color:black;
	}
</style>

<div id = "muestra">
         <div class="container">
		<div class="jumbotron">
		<h1><strong> Contactanos a:</strong> </h1>
      <h4>Esteban Zurita - estebanzurita316@gmail.com</h4>
		  <h4>Luis Veizaga - luisnlbs4@gmail.com</h4>
		  <h4>Ale Siles - alejandra_siles_a@hotmail.com</h4>
		  <h4>Gabriel Lucuy - gabriellucuy@gmail.com</h4>
	   </div>
	   </div>
	 </div>
		 

app/views/welcome/index.html.erb
<style type="text/css">
	body{
		background-color: #043D2C;
		text-align: center;
		color:white;
	}
</style>
		<div id="muestra">
		<h1><strong> Veterinaria</strong> </h1>
		<%= image_tag "principal.jpg", :alt => "Twitter", :title => "logoVeterinaria" , class:"img-circle" ,width:"380px",height:"380px"%>
		<h3>Bienvenido</h3>
	</div>
		<div class="ui vertical buttons">
			<%= link_to 'Clientes', clientes_path , class:"huge ui button,ui inverted orange button" %></br>
			<%= link_to 'Mascotas', mascota_path, class:"huge ui button,ui inverted orange button" %>
		</div>
		<div class="ui vertical buttons">
			<%= link_to 'Veterinarios', veterinarios_path , class:"huge ui button,ui inverted blue button" %></br>
			<%= link_to 'Turnos', turnos_path,class:"huge ui button,ui inverted blue button" %>
			<%= link_to 'Atencion', atencions_path,class:"huge ui button,ui inverted blue button" %>

		</div>
		<div class="ui vertical buttons">
			<%= link_to 'Productos', prodcutos_path ,class:"huge ui button,ui inverted olive button" %>
			<%= link_to 'Venta', venta_path, class:"huge ui button,ui inverted olive button" %>
		</div>