config/routes.rb
Rails.application.routes.draw do

  get '/ventas/:id/cambiar' => 'venta#cambiar'
  get 'atencions/:id/asignar_mascota'=>'atencions#asignar_mascota'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  
  get '/mascota/:id/atenciones' => 'mascota#atenciones'

  get '/clientes/buscar' => 'clientes#buscar'
  get '/mascota/buscar' => 'mascota#buscar'
  get '/veterinarios/buscar' => 'veterinarios#buscar'
  get '/clientes/:id/ventas' => 'clientes#ventas'
  get '/prodcutos/:id/modificar' => 'prodcutos#modificar'
  get '/prodcutos/:id/reabastecer' => 'prodcutos#reabastecer'
  get '/turnos/:id/atendiendo' => 'turnos#atendiendo'
  get '/turnos/:id/atendido' => 'turnos#atendido'

  get 'welcome/index'
  get 'veterinaria'=> 'welcome#index'
  get 'About'=> 'welcome#about'
  get 'Contact'=> 'welcome#contact'
  get 'contact/index'
  get 'about/index'
  resources :atencions
  resources :turnos
  resources :lists
  resources :venta
  resources :clientes
  resources :veterinarios
  resources :mascota
  resources :prodcutos
  resources :clientes

   root 'welcome#index'

end

app/models/atencion.rb
class Atencion < ActiveRecord::Base

	belongs_to :cliente
	belongs_to :mascotum
	belongs_to :veterinario
	validates :anamnesis,:presence=>{message: "No puede estar vacio"}
	validates :temperatura,:presence=>{message: "No puede estar vacio"}
	validates :mucosas,:presence=>{message: "No puede estar vacio"}
	validates :palpacion,:presence=>{message: "No puede estar vacio"}
	validates :diagnostico,:presence=>{message: "No puede estar vacio"}
	validates :tratamiento,:presence=>{message: "No puede estar vacio"}

end

app/controllers/atencions_controller.rb
class AtencionsController < ApplicationController
  before_action :set_atencion, only: [:show, :edit, :update, :destroy]

  # GET /atencions
  # GET /atencions.json
  def index
    @atencions = Atencion.all
  end

  # GET /atencions/1
  # GET /atencions/1.json
  def show
  end

  # GET /atencions/new
  def new
    @atencion = Atencion.new
  end
  def asignar_mascota

     @atencion = Atencion.find(params[:id])
     @atencion.mascotum_id = params[:cliente][:cliente_id]   
     @atencion.save
     respond_to do |format|      
        format.html { redirect_to @atencion, notice: 'Mascota asignada' }
     end
  end
  # GET /atencions/1/edit
  def edit
  end

  # POST /atencions
  # POST /atencions.json
  def create
    @atencion = Atencion.new(atencion_params)

    respond_to do |format|
      if @atencion.save
        format.html { redirect_to @atencion, notice: 'Atencion creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @atencion }
      else
        format.html { render :new }
        format.json { render json: @atencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atencions/1
  # PATCH/PUT /atencions/1.json
  def update
    respond_to do |format|
      if @atencion.update(atencion_params)
        format.html { redirect_to @atencion, notice: 'Cambios guardados!.' }
        format.json { render :show, status: :ok, location: @atencion }
      else
        format.html { render :edit }
        format.json { render json: @atencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atencions/1
  # DELETE /atencions/1.json
  def destroy
    @atencion.destroy
    respond_to do |format|
      format.html { redirect_to atencions_url, notice: 'Atencion eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atencion
      @atencion = Atencion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atencion_params
      params.require(:atencion).permit(:fecha,:anamnesis, :temperatura, :mucosas, :palpacion, :diagnostico, :tratamiento,:cliente_id,:mascotum_id,:veterinario_id)
    end
end

app/helpers/atencions_helper.rb
module AtencionsHelper
end

app/views/atencions/_form.html.erb
<style type="text/css">
   label{
    color:white;
   }
   h1{
     color: white;
   }
</style>
<%= form_for(@atencion) do |f| %>
  <% if @atencion.errors.any? %>
    <div class="container">
    <div class="alert alert-danger" role="alert">
      <font color="black"><h2><%= pluralize(@atencion.errors.count, "error") %> prohibited this atencion from being saved:</h2></font>
      <% @atencion.errors.full_messages.each do |message| %>
         <font color="black"><li><%= message %></li></font>
      <% end %>
    </div>
  </div>
  <% end %>

  <div class="field, container">
    <table class="table">
      <tr>
        <td><%= f.label :Dueño %></td>
        <td><%= f.collection_select(:cliente_id, Cliente.all, :id, :ci)  %></td>
      </tr>
      <%= hidden_field_tag :mascotum_id, nil %>
      <tr>
        <td><%= f.label :Veterinario %></td>
        <td><%= f.collection_select(:veterinario_id, Veterinario.all, :id, :ci) %></td>
      </tr>
      <tr>
        <td><%= f.label :fecha %></td>
        <td><%= f.date_select :fecha %></td>
      </tr>

      <tr>
        <td><%= f.label :anamnesis %></td>
        <td><%= f.text_area :anamnesis, {:id => "lol"} %></td>
      </tr>
      <tr>
        <td><%= f.label :temperatura %></td>
        <td><%= f.number_field :temperatura %></td>
      </tr>
      <tr>
        <td><%= f.label :mucosas %></td>
        <td><%= f.text_area :mucosas %></td>
      </tr>
      <tr>
        <td><%= f.label :palpacion %></td>
        <td><%= f.text_area :palpacion %></td>
      </tr>
      <tr>
        <td><%= f.label :diagnostico %></td>
        <td><%= f.text_area :diagnostico %></td>
      </tr>
      <tr>
        <td><%= f.label :tratamiento %></td>
        <td><%= f.text_area :tratamiento %></td>
      </tr>
    </table>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', class:"big ui button, ui inverted olive button"  %>
  </div>
<% end %>

app/views/atencions/edit.html.erb
<style type="text/css">

  h1{
    color:white;
   }
</style>
<h1>Editar Atencion</h1>

<%= render 'form' %>

<%= link_to 'Ver', @atencion , class:"btn btn-info" %> |
<%= link_to 'Home Mascotas', atencions_path , class:"btn btn-primary"  %>

app/views/atencions/index.html.erb
<style type="text/css">

  h1{
    color:white;
   }

   thead{
    color:white;
   }

    td{
    background-color: white;
   }

</style>
<p id="notice"><%= notice %></p>
<div id="muestra">
<h1>Lista de Atenciones</h1>
<div class="row">
  <div class="col-md-5 col-md-offset-4">

  <table  class="table table-striped">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Cliente</th>
        <th>Mascota nombre</th>
        <th>Veterinario</th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @atencions.each do |atencion| %>
        <tr>
          <td><%= atencion.fecha %></td>
          <td><%if Cliente.find_by(id: atencion.cliente_id) != nil %>
            <%= atencion.cliente.nombre %> <%= atencion.cliente.apellido %>
            <%else%>
            N/A
            <%end%>
          </td>
          <td><% if Mascotum.find_by(id: atencion.mascotum_id) != nil  %>
            <%= atencion.mascotum.nombre %>
            <%else%>
            N/A
            <%end%>
          </td>

          <td><% if Veterinario.find_by(id: atencion.veterinario_id) != nil  %>
            <%= atencion.veterinario.nombre%> <%= atencion.veterinario.apellido%>
            <%else%>
            N/A
            <%end%>
          </td>
          <td><%= link_to 'Ver', atencion, class: "btn btn-info" %></td>
          <td><%= link_to 'Editar', edit_atencion_path(atencion) , class: "btn btn-warning"%></td>
          <td><%= link_to 'Eliminar', atencion, method: :delete, data: { confirm: 'Esta seguro?' } , class: "btn btn-danger"%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>
<br>

<%= link_to 'New Atencion', new_atencion_path , class: "btn btn-success" %>
<a  class="btn btn-primary" href="veterinaria">Home</a>

app/views/atencions/new.html.erb
<style type="text/css">
   h1{
    color:white;
   }
</style>
<h1>Nueva Atencion</h1>

<%= render 'form' %>

<%= link_to 'Lista de Atenciones', atencions_path,  class:"big ui button, ui inverted blue button"  %>

app/views/atencions/show.html.erb
<style type="text/css">
  p{
    color:white;
   }
   td{
    background-color: white;
   }
   thead{
    color:white;
   }
   strong{
    color:white;
   }

</style>
<div id="muestra">
<h1><strong>Datos de la Atencion</strong></h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%if Cliente.find_by(id: @atencion.cliente_id) != nil %>
            <%= @atencion.cliente.nombre %> <%= @atencion.cliente.apellido %>
  <%else%>
            N/A
  <%end%>
</p>
<p>
  <%if@atencion.mascotum_id !=nil%>
  <strong>Mascota:</strong>
  <% if Mascotum.find_by(id: @atencion.mascotum_id) != nil  %>
            <%= @atencion.mascotum.nombre %>
            <%else%>
            N/A
            <%end%>
</p>
<%else%>
   <%= form_tag({:controller => "atencions", :action => "asignar_mascota"}, :method => :get) do %>
    <%= collection_select :cliente, :cliente_id, Mascotum.where(cliente_id:@atencion.cliente_id), :id, :nombre%>
    <%= submit_tag "Asignar" , class: "btn btn-danger" %>
    <% end %>
<%end%>
<p>
  <strong>Veterinario:</strong>
   <% if Veterinario.find_by(id: @atencion.veterinario_id) != nil  %>
            <%= @atencion.veterinario.nombre%> <%= @atencion.veterinario.apellido%>
            <%else%>
            N/A
            <%end%>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @atencion.fecha %>
</p>



<p>
  <strong>Anamnesis:</strong>
  <%= @atencion.anamnesis %>
</p>

<p>
  <strong>Temperatura(°C):</strong>
  <%= @atencion.temperatura %>
</p>

<p>
  <strong>Mucosas:</strong>
  <%= @atencion.mucosas %>
</p>

<p>
  <strong>Palpacion:</strong>
  <%= @atencion.palpacion %>
</p>

<p>
  <strong>Diagnostico:</strong>
  <%= @atencion.diagnostico %>
</p>

<p>
  <strong>Tratamiento:</strong>
  <%= @atencion.tratamiento %>
</p>
</div>

<%= link_to 'Edit', edit_atencion_path(@atencion), class: "btn btn-warning"  %> |
<%= link_to 'Back', atencions_path , class: "btn btn-primary" %>